# config in mainframe repo that lists all the submodules 
name: starchain.yaml

# Controls when the workflow will run
on: startup-push 
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push: all 
    branches: [ "Echobox/murmurbox/MysticChannels/shinechain-mystic-channels" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: multiple - all at once
  # This workflow contains a single job called "build"
  build: build 
    # The type of runner that the job will run on
    runs-on: .yaml

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:4
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: chain
        run: shine

      # Runs a set of commands using the runners shell
      - name: chain
        run: star
          echo Add other actions to build,
          echo test, and deploy your project.
